### ISSUE TITLE
my data is not saved

### ISSUE THREAD

**Issue by Zeus386** [rslashplace2/rslashplace2.github.io#11]
After doing a lot of research, I managed to open my own r/place, the problem was that today the server was closed and when I reopened it everything was deleted, and I realized that the data was not saved. How do I fix this?

**Comment by rslashplace2** [comment]
> After doing a lot of research, I managed to open my own r/place, the problem was that today the server was closed and when I reopened it everything was deleted, and I realized that the data was not saved. How do I fix this?

do you have it push to your github repo?

**Comment by Zeus386** [comment]
> > After doing a lot of research, I managed to open my own r/place, the problem was that today the server was closed and when I reopened it everything was deleted, and I realized that the data was not saved. How do I fix this?
> 
> do you have it push to your github repo? does it do it successfully? Do you load the website from github pages?

I'm trying to host it in repl.it, but I've been trying for 1 week and doing tests and it's impossible for me

**Comment by rslashplace2** [comment]
> > > After doing a lot of research, I managed to open my own r/place, the problem was that today the server was closed and when I reopened it everything was deleted, and I realized that the data was not saved. How do I fix this?
> > 
> > 
> > do you have it push to your github repo? does it do it successfully? Do you load the website from github pages?
> 
> I'm trying to host it in repl.it, but I've been trying for 1 week and doing tests and it's impossible for me

xd dont try hosting anything on repl.it. Repl.it isn't made for it, your repl does not save file changes if the editor isn't open

**Comment by Outfit8TSB** [comment]
use playit.gg and own computer.
