### ISSUE TITLE
Canvas size update

### ISSUE THREAD

**Issue by epsseniyer** [rslashplace2/rslashplace2.github.io#25]
## I need to ask Can they Update weight to 4000
********
So please do it we need update!

**Comment by Zekiah-A** [comment]
What do you mean by "size update"? Do you want a biggest canvas, or different zoom options, etc..?

**Comment by Zeus386** [comment]
> What do you mean by "size update"? Do you want a bigger canvas, or different zoom options, etc..?

My canvas is currently 500x500 and I would like to change it to 1000x1000 in the future.
