### ISSUE TITLE
bring back the cool 1000x1000 canvas and cool original 32 color palette. (NOW UPLOADED TO REDDIT.)

### ISSUE THREAD

**Issue by Outfit8TSB** [rslashplace2/rslashplace2.github.io#278]
### bring back the cool 1000x1000 canvas and cool original 32 color palette.
The Canvas Shrink into 500x500 and palette shrunk into 12, and i want 1000x1000 and 32 colors back. it's cooler.
### Problems
they are so small, i can barely draw Battle For Dream Island Text with that.
after 6 batch is added at 4/7. there was no change. 
### peoples agree with me:
randomplacer u/Admirable-Grass-4490
### Compare:
![image](https://github.com/rslashplace2/rslashplace2.github.io/assets/167604853/278f3456-ed65-4a7d-a0f5-2f14603ab317)
### Status
**Canvas Status**
Canvas Expanded to 500 x 750 Canvas (Canvas Expand Percentage Ratio: 37.5%) (625000 Pixel Remaining)
**Palette Status**
No Changes (Palette Expand Ratio: 56.25%) (Color Remaining: 14)
as of 05-23
**Canvas Status**
Canvas Expanded to 750 x 750 Canvas (Canvas Expand Percentage Ratio: 56.25%) (437500 Pixel Remaining)
**Palette Status**
No Changes (Palette Expand Ratio: 56.25%) (Color Remaining: 14)

**Comment by Zekiah-A** [comment]
This is technically a canvas issue, not a software issue, but I'll consider it anyway. Thanks for the message.

Also I see you are hosting your own version of the game, if you have any issues with the software feel free to ask and I'll try my best to help 👍

**Comment by Outfit8TSB** [comment]
thanks, i will update the situation on main comment.

**Comment by Outfit8TSB** [comment]
### as of 5-23:
i expected that palette going back to before darkplace.live, where we had so much fun, darkplace.live was not fun april fools prank at all. we lost 32 color palette, 1000 x 1000 pixel canvas, and most of all, Battle For Dream Island Fans Drawing. where is fun in darkplace.live? Nowhere. all fun is gone with my bfdi void covered square(2023-2023, Overwritten by Iran flag and everything was absorbed to transflag). now i miss good old times on 1000 x 1000 canvas with 32 colors. i had to create a fork of rplace.live called Outfit8TSB.github.io. darkplace.live is a worst april fools prank, now april fools is ruined. i want to draw talking tom, with 32 colors. i cannot stand with 18 color palette anymore. 
![image](https://github.com/rslashplace2/rslashplace2.github.io/assets/167604853/374d0ddb-2229-44d7-a4bf-07fbcb8945d1)

**Comment by Outfit8TSB** [comment]
well. at least i got cyan

**Comment by Zekiah-A** [comment]
How is infiniplace going? Also do you have discord?

**Comment by Outfit8TSB** [comment]
going to coming out in 7/23 or sooner. and no, i don't have discord.

**Comment by Zekiah-A** [comment]
> going to coming out in 7/23 or sooner. and no, i don't have discord.

if you are just running the server yourself, I can add a link to your canvas from the post menu in the main site :+1:

**Comment by Outfit8TSB** [comment]
Ok, thank you.

**Comment by Outfit8TSB** [comment]
this issue will be closed, as it will no longer in effect.
