### ISSUE TITLE
Create a private server

### ISSUE THREAD

**Issue by Zeus386** [rslashplace2/rslashplace2.github.io#3]
I have spent many hours fascinated with the work you have achieved, the truth is that it is very well done. The problem is that I would like to be able to have my own r/place for my discord server, so I would have to create another server, how could I do it?

**Comment by Zekiah-A** [comment]
Very possible! This can probably be done with a few modifications to the site, as we have not yet made it to be fully configurable by people. If you are okay with changing a few lines of javascript, I can give you guidance on how to get it up and running yourself when I'm next available

**Comment by rslashplace2** [comment]
you could also try canv.tk

**Comment by Zeus386** [comment]
> you could also try canv.tk it works slightly differently but it is built for 3rd party stuff. i can send you the server files

Thanks for the suggestion, but the truth is that I like the original style better, the problem is that I'm new to these things, and I don't even know where to start.

**Comment by Zeus386** [comment]
> Very possible! This can probably be done with a few modifications to the site, as we have not yet made it to be fully configurable by people. If you are okay with changing a few lines of javascript, I can give you guidance on how to get it up and running yourself when I'm next available

If it's not too much trouble guide me 😅

**Comment by Zeus386** [comment]
> you could also try canv.tk it works slightly differently but it is built for 3rd party stuff. i can send you the server files

Could you help me then please? 😅

**Comment by Tacktiik** [comment]
> Very possible! This can probably be done with a few modifications to the site, as we have not yet made it to be fully configurable by people. If you are okay with changing a few lines of javascript, I can give you guidance on how to get it up and running yourself when I'm next available

I am also looking to make a private server

**Comment by Zekiah-A** [comment]
@rslashplace2

**Comment by Zekiah-A** [comment]
In the future, we should have an official way to make private servers, using the main rplace.tk site. Possibly this can be done by allowing people to self host server.JS, and then connect to it using a "switch server" feature on rplace.tk, to use their own custom server address with the same frontend
