### ISSUE TITLE
[Best practices] Do not commit "node_modules" folder

### ISSUE THREAD

**Issue by duke1102** [rslashplace2/rslashplace2.github.io#51]
Hey,

just wanted to let you know that you shouldn't commit your whole `node_modules` folder to a git repository.  
The main reason is that this folder can grow in size and LOTS of small size files very quickly.  
https://www.positronx.io/should-i-commit-the-node_modules-folder-to-git/  

You can just create a `.gitignore` file and add the `node_modules` folder in there, then git will ignore it.

**Comment by rslashplace2** [comment]
fixed
